-- French localization file for frFR.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0");
local L = AceLocale:NewLocale("ElvUI", "frFR");
if not L then return; end

--TEMP
L["A taint has occured that is preventing you from using the queue system. Please reload your user interface and try again."] = "Une alteration s'est produite et vous empêche d'utiliser la file d'attente. Veuillez recharger votre interface utilisateur et essayer à nouveau."

--ActionBars
L["Binding"] = "Raccourcis"
L["Key"] = "Touche"
L['KEY_ALT'] = "A"
L['KEY_CTRL'] = "C"
L['KEY_DELETE'] = "Suppr"
L['KEY_HOME'] = "Hm"
L['KEY_INSERT'] = "Ins"
L['KEY_MOUSEBUTTON'] = "M"
L['KEY_MOUSEWHEELDOWN'] = "MwD"
L['KEY_MOUSEWHEELUP'] = "MwU"
L['KEY_NUMPAD'] = "N"
L['KEY_PAGEDOWN'] = "PD"
L['KEY_PAGEUP'] = "PU"
L['KEY_SHIFT'] = "S"
L['KEY_SPACE'] = "SpB"
L["No bindings set."] = "Aucune assignation"
L['Remove Bar %d Action Page'] = "Retirer la pagination de la barre d'action"
L['Trigger'] = "Déclencheur"

--Bags
L['Delete Grays'] = "Détruire les objets gris."
L['Hold Control + Right Click:'] = "Contrôle enfoncée + Clic droit"
L['Hold Shift + Drag:'] = "Majscule enfoncée + Déplacer"
L['Hold Shift:'] = "Maintenir MAJ:"
L['Purchase'] = "Acheter"
L['Reset Position'] = "Réinitialiser la position"
L['Sort Bags'] = "Trier les sacs"
L['Sort Tab'] = true; --Not used, yet?
L['Stack Bags to Bank'] = "Empiler des Sacs vers la Banque"
L['Stack Bank to Bags'] = "Empiler de la Banque vers les Sacs"
L['Stack Items'] = "Empilement des objets"
L['Temporary Move'] = "Bouger temporairement";
L['Toggle Bags'] = "Afficher les sacs"
L['Vendor Grays'] = "Vendre les objets gris"

--Chat
L['AFK'] = "ABS" --Also used in datatexts and tooltip
L['DND'] = "NPD" --Also used in datatexts and tooltip
L['G'] = "G"
L['I'] = "I"
L['IL'] = "IL"
L['Invalid Target'] = "Cible incorrecte"
L['O'] = "O"
L['P'] = "Gr"
L['PL'] = "CdG"
L['R'] = "R"
L['RL'] = "RL"
L['RW'] = "RW"
L['says'] = "dit"
L['whispers'] = "chuchote"
L['yells'] = "crie"

--DataTexts
L['(Hold Shift) Memory Usage'] = "(Maintenir MAJ) Utilisation de la Mémoire."
L['AP'] = "PA"
L['AVD: '] = "AVD: "
L["Avoidance Breakdown"] = "Répartition de l'évitement"
L['Bandwidth'] = "Bande passante"
L['Bases Assaulted'] = "Bases assaillis"
L['Bases Defended'] = "Bases défendues"
L['Carts Controlled'] = "Chariots contrôlés"
L["Character: "] = "Personnage: "
L['Chest'] = "Torse"
L["Combat Time"] = "Durée du Combat"
L["copperabbrev"] = "|cffeda55fc|r" --Also used in Bags
L['Defeated'] = "Defaite"
L["Deficit:"] = "Déficit:"
L['Demolishers Destroyed'] = "Démolisseurs détruits"
L['Download'] = "Téléchargement"
L["DPS"] = "DPS"
L["Earned:"] = "Gagné:"
L['Feet'] = "Pieds"
L['Flags Captured'] = "Drapeaux capturés"
L['Flags Returned'] = "Drapeaux retournés"
L['Friends List'] = "Liste d'amis"
L['Friends'] = "Amis" --Also in Skins
L['Galleon'] = "Galion"
L['Gates Destroyed'] = "Portes détruites"
L["goldabbrev"] = "|cffffd700g|r" --Also used in Bags
L['Graveyards Assaulted'] = "Cimetières assaillis"
L['Graveyards Defended'] = "Cimetières défendus"
L['Hands'] = "Mains"
L['Head'] = "Tête"
L['Hit'] = "Toucher"
L['Home Latency:'] = "Latence du Domicile:"
L['HP'] = "PdS"
L["HPS"] = "HPS"
L['Legs'] = "Jambes"
L['lvl'] = "niveau"
L['Main Hand'] = "Main droite"
L['Mitigation By Level: '] = "Réduction par niveau: "
L['Nalak'] = "Nalak"
L['No Guild'] = "Non Guildé"
L['Offhand'] = "Main gauche"
L['Oondasta'] = "Oondasta"
L['Orb Possessions'] = "Orbes obtenues"
L["Profit:"] = "Profit:"
L["Reset Data: Hold Shift + Right Click"] = "RAZ des données: Shift + Clic droit"
L["Saved Raid(s)"] = "Raid(s) Sauvegardé(s)"
L["Server: "] = "Serveur: "
L['Session:'] = "Session:"
L['Sha of Anger'] = "Sha de la colère"
L['Shoulder'] = "Épaule"
L["silverabbrev"] = "|cffc7c7cfs|r" --Also used in Bags
L['SP'] = "PdS"
L["Spent:"] = "Dépensé: "
L['Stats For:'] = "Stats pour:"
L['Total CPU:'] = "Charge du CPU:"
L['Total Memory:'] = "Mémoire totale:"
L["Total: "] = "Total: "
L['Towers Assaulted'] = "Tours attaquées"
L['Towers Defended'] = "Tours défendues"
L['Undefeated'] = "Invaincu"
L['Unhittable:'] = "Intouchable:"
L['Victory Points'] = "Points de Victoire"
L['Waist'] = "Ceinture"
L["World Boss(s)"] = "Boss Mondiaux"
L['Wrist'] = "Poignets"

--DebugTools
L["%s: %s tried to call the protected function '%s'."] = "%s: %s a essayé d'appeler la fonction protégée '%s'."
L["No locals to dump"] = "Aucunes données à vider"

--Distributor
L['%s is attempting to share his filters with you. Would you like to accept the request?'] = "%s tente de partager ses profils avec vous. Voulez-vous accepter la demande?"
L['%s is attempting to share the profile %s with you. Would you like to accept the request?'] = "%s tente de partager le profil %s avec vous. Voulez-vous accepter la demande?"
L["Data From: %s"] = "Donnée de: %s"
L['Filter download complete from %s, would you like to apply changes now?'] = "Téléchargement du filtre de %s complet, voulez-vous appliquer les changements maintenant ?" --Need review
L["Lord! It's a miracle! The download up and vanished like a fart in the wind! Try Again!"] = "Seigneur ! C'est un miracle ! Le téléchargement monte et a disparu comme une pet dans le vent! Essayez encore !"  --Need review for special english terms: the download up
L['Profile download complete from %s, but the profile %s already exists. Change the name or else it will overwrite the existing profile.'] = "Téléchargement du profil de %s complet, néanmoins le profil de % existe déjà. Changez le nom ou bien il écrasera le profil existant."
L['Profile download complete from %s, would you like to load the profile %s now?'] = "Téléchargement du profil de %s complet, voulez-vous charger le profil %s maintenant?"
L['Profile request sent. Waiting for response from player.'] = "Requête du profil envoyé. En attente de la reponse du joueur."
L['Request was denied by user.'] = "La requête a ete refusée par l'utilisateur."
L['Your profile was successfully recieved by the player.'] = "Votre profil a été reçu avec succès par le joueur."

--Install
L["Auras Set"] = "Configuration des Auras"
L["Auras System"] = "Système d'Auras"
L['Caster DPS'] = "DPS Distance"
L["Chat Set"] = "Chat configuré"
L["Chat"] = "Discussion"
L['Choose a theme layout you wish to use for your initial setup.'] = "Choisissez un modèle de thème que vous souhaitez utiliser pour votre configuration initiale."
L["Classic"] = "Classique"
L["Click the button below to resize your chat frames, unitframes, and reposition your actionbars."] = "Cliquez sur le bouton ci-dessous pour redimensionner vos fenêtres de chat, vos cadres d'unités et repositionner vos barres d'actions."
L['Config Mode:'] = "Mode Configuration:"
L["CVars Set"] = "CVars configurés"
L["CVars"] = "CVars"
L['Dark'] = "Sombre"
L['Disable'] = "Désactiver"
L["ElvUI Installation"] = "Installation d'ElvUI"
L["Finished"] = "Terminé"
L['Grid Size:'] = "Taille de la Grille:"
L['Healer'] = "Soigneur"
L["High Resolution"] = "Haute Résolution"
L["high"] = "Haute"
L['Icons Only'] = "Icônes seulement" --Also used in Bags
L["If you have an icon or aurabar that you don't want to display simply hold down shift and right click the icon for it to disapear."] = "Si vous avez une icône ou une barre d'aura que vous ne souhaitez pas afficher il suffit de maintenir la touche MAJ enfoncée et d'effectuer un clic droit sur l'icône correspondante pour la faire disparaitre."
L["Importance: |cff07D400High|r"] = "Importance: |cff07D400Haute|r"
L["Importance: |cffD3CF00Medium|r"] = "Importance: |cffD3CF00Moyenne|r"
L["Importance: |cffFF0000Low|r"] = "Importance: |cffFF0000Faible|r"
L["Installation Complete"] = "Installation terminée"
L['Integrated'] = "Intégré"
L["Layout Set"] = "Disposition configurée"
L["Layout"] = "Disposition"
L["Lock"] = "Verrouiller"
L['Low Resolution'] = "Basse résolution"
L["low"] = "Faible"
L["Movers unlocked. Move them now and click Lock when you are done."] = "Cadres déverrouillés. Déplacez-les et cliquez sur Verrouiller une fois terminé."
L['Nudge'] = true;
L['Physical DPS'] = "DPS Physique"
L["Pixel Perfect Set"] = "Réglage Pixel Parfait"
L["Pixel Perfect"] = "Pixel Parfait"
L["Please click the button below so you can setup variables and ReloadUI."] = "Pour configurer les variables et recharger l'interface, cliquez sur le bouton ci-dessous."
L["Please click the button below to setup your CVars."] = "Pour configurer les CVars, cliquez sur le bouton ci-dessous."
L["Please press the continue button to go onto the next step."] = "Pour passer à l'étape suivante, cliquez sur le bouton Continuer."
L["Resolution Style Set"] = "Paramètre de résolution configuré"
L["Resolution"] = "Résolution"
L["Select the type of aura system you want to use with ElvUI's unitframes. The integrated system utilizes both aura-bars and aura-icons. The icons only system will display only icons and aurabars won't be used. The classic system will configure your auras to be default."] = "Sélectionnez le type de système aura que vous souhaitez utiliser avec UnitFrames ElvUI. Le système intégré utilise à la fois les barres d'Auras et les icônes d'Auras. Le systeme icône seul va afficher uniquement les icônes et barres d'auras ne sera pas utilisé. Le système classique permet de configurer vos Auras par défaut."
L["Setup Chat"] = "Configurer le Chat."
L["Setup CVars"] = "Configurer les CVars"
L["Skip Process"] = "Passer cette étape"
L["Sticky Frames"] = "Cadres adhésifs"
L['Tank'] = "Tank"
L["The chat windows function the same as Blizzard standard chat windows, you can right click the tabs and drag them around, rename, etc. Please click the button below to setup your chat windows."] = "La fenêtre de chat d'ElvUi utilise les même fonctions que celle Blizzard, vous pouvez faire un clic droit sur un onglet pour le déplacer, le renommer, etc."
L["The in-game configuration menu can be accesses by typing the /ec command or by clicking the 'C' button on the minimap. Press the button below if you wish to skip the installation process."] = "Le menu de configuration est accessible en tapant la commande /ec ou en cliquant sur le bouton 'C' sur la Minicarte. Cliquez sur le bouton ci-dessous si vous voulez passer le processus d'installation."
L['The Pixel Perfect option will change the overall apperance of your UI. Using Pixel Perfect is a slight performance increase over the traditional layout.'] = "Le thème Pixel Parfait change entièrement l'apparence de votre UI. Utiliser le thème Piwel Parfait consomme moins de ressource que le thème traditionnel."
L["Theme Set"] = "Choisir le thème"
L['Theme Setup'] = "Configuration du thème"
L["This install process will help you learn some of the features in ElvUI has to offer and also prepare your user interface for usage."] = "Ce programme d'installation vous aidera à découvrir quelques fonctionnalités qu'ElvUI offre et préparera également votre interface à son utilisation."
L["This is completely optional."] = "Ceci est totalement optionnel."
L["This part of the installation process sets up your chat windows names, positions and colors."] = "Cette partie du processus d'installation configure les noms, positions et couleurs de vos fenêtres de chat."
L["This part of the installation process sets up your World of Warcraft default options it is recommended you should do this step for everything to behave properly."] = "Cette partie du processus d'installation paramètrera vos options par défaut de World of Warcraft. Il est recommandé d'effectuer cette étape afin que tout fonctionne correctement."
L["This resolution doesn't require that you change settings for the UI to fit on your screen."] = "Cette résolution ne nécessite pas que vous modifiez les paramètres de l'interface utilisateur pour s'adapter à votre écran."
L["This resolution requires that you change some settings to get everything to fit on your screen."] = "Cette résolution nécessite que vous modifiez les paramètres de l'interface utilisateur pour s'adapter sur votre écran."
L["This will change the layout of your unitframes, raidframes, and datatexts."] = "Ceci changera la disposition des cadres d'unités, des cadres de Raid et des Textes d'informations."
L['Trade'] = "Métiers"
L['Using the healer layout it is highly recommended you download the addon Clique to work side by side with ElvUI.'] = "Il est hautement recommandé de télécharger l'addon Clique si vous utilisez l'interface de soigneur d'ElvUI."
L['Using this option will cause your borders around frames to be 1 pixel wide instead of 3 pixel. You may have to finish the installation to notice a differance. By default this is enabled.'] = "L'utilisation de cette option modifiera vos bordures d'images à 1 pixel de large au lieu de 3 pixels. Vous devez terminer l'installation pour constater une différence. Par défaut cette option est activée."
L["Welcome to ElvUI version %s!"] = "Bienvenue sur la version %s d'ElvUI!"
L["You are now finished with the installation process. If you are in need of technical support please visit us at http://www.tukui.org."] = "Vous avez maintenant terminé le processus d'installation. Si vous avez besoin d'un support technique, merci de vous rendre sur http://www.tukui.org"
L['You can always change fonts and colors of any element of elvui from the in-game configuration.'] = "Vous pouvez toujours modifier les polices et les couleurs de n'importe quel élément d'Elvui dans la configuration du jeu."
L["You can now choose what layout you wish to use based on your combat role."] = "Vous pouvez maintenant choisir quelle disposition vous souhaitez utiliser en fonction de votre rôle lors d'un combat."
L["You may need to further alter these settings depending how low you resolution is."] = "Vous devrez peut-être encore modifier ces paramètres en fonction d'un changement de résolution."
L["Your current resolution is %s, this is considered a %s resolution."] = "Votre résolution actuelle est %s, elle est donc considérée comme une %s Résolution."

--Misc
L['Bars'] = true; --Also used in UnitFrames
L['Calendar'] = true;
L["Can't Roll"] = true;
L['Disband Group'] = true;
L['Empty Slot'] = true;
L["Enable"] = true; --Doesn't fit a section since it's used a lot of places
L['Experience'] = true;
L['Fishy Loot'] = true;
L['Left Click:'] = true; --layout\layout.lua
L['Raid Menu'] = true;
L['Remaining:'] = true;
L['Rested:'] = true;
L['Right Click:'] = true; --layout\layout.lua
L['Show BG Texts'] = true; --layout\layout.lua
L['Toggle Chat Frame'] = true; --layout\layout.lua
L['Toggle Configuration'] = true; --layout\layout.lua
L['XP:'] = true;
L["You don't have permission to mark targets."] = true;
L['ABOVE_THREAT_FORMAT'] = '%s: %.0f%% [%.0f%% above |cff%02x%02x%02x%s|r]'

--Movers
L[' Frames'] = true;
L['Alternative Power'] = true;
L['Arena Frames'] = true; --Also used in UnitFrames
L["Auras Frame"] = true;
L['Bags'] = true; --Also in DataTexts
L['Bar '] = true; --Also in ActionBars
L['BNet Frame'] = true;
L['Boss Button'] = true;
L['Boss Frames'] = true; --Also used in UnitFrames
L["Experience Bar"] = true;
L['Focus Castbar'] = true;
L['Focus Frame'] = true; --Also used in UnitFrames
L['FocusTarget Frame'] = true; --Also used in UnitFrames
L["GM Ticket Frame"] = true;
L["Left Chat"] = true;
L["Loot / Alert Frames"] = true;
L["Loot Frame"] = true;
L['Loss Control Icon'] = true;
L['MA Frames'] = true;
L['Micro Bar'] = true; --Also in ActionBars
L['Minimap'] = true;
L['MT Frames'] = true;
L['Party Frames'] = true; --Also used in UnitFrames
L['Pet Bar'] = true; --Also in ActionBars
L['Pet Frame'] = true; --Also used in UnitFrames
L['PetTarget Frame'] = true; --Also used in UnitFrames
L['Player Castbar'] = true;
L['Player Frame'] = true; --Also used in UnitFrames
L['Raid 1-'] = true;
L["Reputation Bar"] = true;
L["Right Chat"] = true;
L['Stance Bar'] = true; --Also in ActionBars
L['Target Castbar'] = true;
L['Target Frame'] = true; --Also used in UnitFrames
L['TargetTarget Frame'] = true; --Also used in UnitFrames
L['Tooltip'] = true;
L['Totems'] = true;
L["Vehicle Seat Frame"] = true;
L['Watch Frame'] = true;
L['Weapons'] = true;

--NamePlates
L['Discipline'] = true;
L['Holy'] = true;
L['Mistweaver'] = true;
L['Restoration'] = true;

--Prints
L[" |cff00ff00bound to |r"] = true;
L["%s frame(s) has a conflicting anchor point, please change either the buff or debuff anchor point so they are not attached to each other. Forcing the debuffs to be attached to the main unitframe until fixed."] = true;
L["All keybindings cleared for |cff00ff00%s|r."] = true;
L['Already Running.. Bailing Out!'] = true;
L['Battleground datatexts temporarily hidden, to show type /bgstats or right click the "C" icon near the minimap.'] = true;
L['Battleground datatexts will now show again if you are inside a battleground.'] = true;
L['Binds Discarded'] = true;
L['Binds Saved'] = true;
L['Confused.. Try Again!'] = true;
L['Deleted %d gray items. Total Worth: %s'] = true;
L['No gray items to delete.'] = true;
L['No gray items to sell.'] = true;
L['The spell "%s" has been added to the Blacklist unitframe aura filter.'] = true;
L['Vendored gray items for:'] = true;
L["You don't have enough money to repair."] = true;
L['You must be at a vendor.'] = true;
L['Your items have been repaired for: '] = true;
L['Your items have been repaired using guild bank funds for: '] = true;
L["Your version of ElvUI is out of date. You can download the latest version from http://www.tukui.org"] = true;
L['|cFFE30000Lua error recieved. You can view the error message when you exit combat.'] = true;
L['LOGIN_MSG'] = "Welcome to %sElvUI|r version %s%s|r, type /ec to access the in-game configuration menu. If you are in need of technical support you can visit us at http://www.tukui.org"

--Static Popups
L["A setting you have changed will change an option for this character only. This setting that you have changed will be uneffected by changing user profiles. Changing this setting requires that you reload your User Interface."] = true;
L["Are you sure you want to delete all your gray items?"] = true;
L["Are you sure you want to disband the group?"] = true;
L["Are you sure you want to reset every mover back to it's default position?"] = true;
L["Because of the mass confusion caused by the new aura system I've implemented a new step to the installation process. This is optional. If you like how your auras are setup go to the last step and click finished to not be prompted again. If for some reason you are prompted repeatedly please restart your game."] = true;
L["Can't buy anymore slots!"] = true;
L['Disable Warning'] = true;
L['Discard'] = true;
L['Do you swear not to post in technical support about something not working without first disabling the addon/module combination first?'] = true;
L["Hover your mouse over any actionbutton or spellbook button to bind it. Press the escape key or right click to clear the current actionbutton's keybinding."] = true;
L['I Swear'] = true;
L['Oh lord, you have got ElvUI and Tukui both enabled at the same time. Select an addon to disable.'] = true;
L["One or more of the changes you have made require a ReloadUI."] = true;
L["One or more of the changes you have made will effect all characters using this addon. You will have to reload the user interface to see the changes you have made."] = true;
L['Save'] = true;
L["You have changed the pixel perfect option. You will have to complete the installation process to remove any graphical bugs."] = true;
L['You have changed your UIScale, however you still have the AutoScale option enabled in ElvUI. Press accept if you would like to disable the Auto Scale option.'] = true;
L['You must purchase a bank slot first!'] = true;
L["INCOMPATIBLE_ADDON"] = "The addon %s is not compatible with ElvUI's %s module. Please select either the addon or the ElvUI module to disable."

--Tooltip
L['Count'] = true;
L['Targeted By:'] = true;

--Tutorials
L['A raid marker feature is available by pressing Escape -> Keybinds scroll to the bottom under ElvUI and setting a keybind for the raid marker.'] = true;
L['ElvUI has a dual spec feature which allows you to load different profiles based on your current spec on the fly. You can enable this from the profiles tab.'] = true;
L['For technical support visit us at http://www.tukui.org.'] = true;
L['If you accidently remove a chat frame you can always go the in-game configuration menu, press install, go to the chat portion and reset them.'] = true
L['If you are experiencing issues with ElvUI try disabling all your addons except ElvUI, remember ElvUI is a full UI replacement addon, you cannot run two addons that do the same thing.'] = true;
L['The buff panel to the right of minimap is a list of your consolidated buffs. You can disable it in Buffs and Debuffs options of ElvUI.'] = true;
L['The focus unit can be set by typing /focus when you are targeting the unit you want to focus. It is recommended you make a macro to do this.'] = true;
L['To move abilities on the actionbars by default hold shift + drag. You can change the modifier key from the actionbar options menu.'] = true;
L['To setup which channels appear in which chat frame, right click the chat tab and go to settings.'] = true;
L['Using the /farmmode <size> command will spawn a larger minimap on your screen that can be moved around, very useful when farming.'] = true;
L['You can access copy chat and chat menu functions by mouse over the top right corner of chat panel and left/right click on the button that will appear.'] = true;
L['You can see someones average item level of their gear by holding shift and mousing over them. It should appear inside the tooltip.'] = true;
L['You can set your keybinds quickly by typing /kb.'] = true;
L['You can toggle the microbar by using your middle mouse button on the minimap you can also accomplish this by enabling the actual microbar located in the actionbar settings.'] = true;
L['You can use the /resetui command to reset all of your movers. You can also use the command to reset a specific mover, /resetui <mover name>.\nExample: /resetui Player Frame'] = true;

--UnitFrames
L['Ghost'] = true;
L['Offline'] = true;