-- Russian localization file for ruRU.
local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("ElvUI", "ruRU")
if not L then return; end

--TEMP
L["A taint has occured that is preventing you from using the queue system. Please reload your user interface and try again."] = "Произошла ошибка, которая не позволит встать в очередь. Пожалуйста, перезагрузите интерфейс и попробуйте снова"

--ActionBars
L["Binding"] = "Назначение"
L["Key"] = "Клавиша"
L['KEY_ALT'] = "A"
L['KEY_CTRL'] = "C"
L['KEY_DELETE'] = "Del"
L['KEY_HOME'] = "Hm"
L['KEY_INSERT'] = "Ins"
L['KEY_MOUSEBUTTON'] = "M"
L['KEY_MOUSEWHEELDOWN'] = "MwD"
L['KEY_MOUSEWHEELUP'] = "MwU"
L['KEY_NUMPAD'] = "N"
L['KEY_PAGEDOWN'] = "PD"
L['KEY_PAGEUP'] = "PU"
L['KEY_SHIFT'] = "S"
L['KEY_SPACE'] = "SpB"
L["No bindings set."] = "Нет назначений"
L['Remove Bar %d Action Page'] = "Удалить панель %d из списка переключаемых"
L['Trigger'] = "Триггер"

--Bags
L['Delete Grays'] = "Удалить предметы серого качества"
L['Hold Control + Right Click:'] = "Зажать control + ПКМ:"
L['Hold Shift + Drag:'] = "Зажать shift и перетаскивать:"
L['Hold Shift:'] = "С зажатым shift'ом:"
L['Purchase'] = "Приобрести слот"
L['Reset Position'] = "Сбросить позицию"
L['Sort Bags'] = "Сортировать"
L['Sort Tab'] = true; --Not used, yet?
L['Stack Bags to Bank'] = "Сложить в банк"
L['Stack Bank to Bags'] = "Сложить в сумки"
L['Stack Items'] = "Собрать предметы"
L['Temporary Move'] = "Временное перемещение"
L['Toggle Bags'] = "Показать сумки"
L['Vendor Grays'] = "Продавать серые предметы"

--Chat
L['AFK'] = "АФК" --Also used in datatexts and tooltip
L['DND'] = "ДНД" --Also used in datatexts and tooltip
L['G'] = "Г"
L['I'] = "П"
L['IL'] = "ЛП"
L['Invalid Target'] = "Неверная цель"
L['O'] = "Оф"
L['P'] = "Гр"
L['PL'] = "Лидер гр."
L['R'] = "Р"
L['RL'] = "РЛ"
L['RW'] = "Объявление"
L['says'] = "говорит"
L['whispers'] = "шепчет"
L['yells'] = "кричит"

--DataTexts
L['(Hold Shift) Memory Usage'] = "(Зажать Shift) Использование памяти"
L['AP'] = "Сила Ат."
L['AVD: '] = "Защита: "
L["Avoidance Breakdown"] = "Распределение защиты"
L['Bandwidth'] = "Канал"
L['Bases Assaulted'] = "Штурмы баз"
L['Bases Defended'] = "Оборона баз"
L['Carts Controlled'] = "Захваты вагонеток"
L["Character: "] = "Персонаж: "
L['Chest'] = "Грудь"
L["Combat Time"] = "В бою"
L["copperabbrev"] = "|cffeda55fм|r" --Also used in Bags
L['Defeated'] = "Убит"
L["Deficit:"] = "Убыток:"
L['Demolishers Destroyed'] = "Разрушителей уничтожено"
L['Download'] = "Загрузка"
L["DPS"] = "УВС"
L["Earned:"] = "Заработано"
L['Feet'] = "Ступни"
L['Flags Captured'] = "Захваты флага"
L['Flags Returned'] = "Возвраты флага"
L['Friends List'] = "Список друзей"
L['Friends'] = "Друзья" --Also in Skins
L['Galleon'] = "Галлеон"
L['Gates Destroyed'] = "Врат разрушено"
L["goldabbrev"] = "|cffffd700з|r" --Also used in Bags
L['Graveyards Assaulted'] = "Штурмы кладбищ"
L['Graveyards Defended'] = "Оборона кладбищ"
L['Hands'] = "Кисти рук"
L['Head'] = "Голова"
L['Hit'] = "Метк."
L['Home Latency:'] = "Локальная задержка: "
L['HP'] = "+ Исцел."
L["HPS"] = "ИВС"
L['Legs'] = "Ноги"
L['lvl'] = "ур."
L['Main Hand'] = "Правая рука"
L['Mitigation By Level: '] = "Снижение на уровне: "
L['Nalak'] = "Налак"
L['No Guild'] = "Нет гильдии"
L['Offhand'] = "Левая рука"
L['Oondasta'] = "Ундаста"
L['Orb Possessions'] = "Захваты сферы"
L["Profit:"] = "Прибыль:"
L["Reset Data: Hold Shift + Right Click"] = "Сбросить нанные: Shift + ПКМ"
L["Saved Raid(s)"] = "Сохраненные рейды"
L["Server: "] = "На сервере:"
L['Session:'] = "За сеанс:"
L['Sha of Anger'] = "Ша Злости"
L['Shoulder'] = "Плечо"
L["silverabbrev"] = "|cffc7c7cfс|r" --Also used in Bags
L['SP'] = "+ Закл."
L["Spent:"] = "Потрачено:"
L['Stats For:'] = "Статистика для:"
L['Total CPU:'] = "Использование процессора:"
L['Total Memory:'] = "Всего памяти:"
L["Total: "] = "Всего: "
L['Towers Assaulted'] = "Штурмы башен"
L['Towers Defended'] = "Оборона башен"
L['Undefeated'] = "Не убит"
L['Unhittable:'] = "Полная защита от ударов"
L['Victory Points'] = "Очки победы"
L['Waist'] = "Пояс"
L["World Boss(s)"] = "Мировые боссы"
L['Wrist'] = "Запястья"

--DebugTools
L["%s: %s tried to call the protected function '%s'."] = "%s: %s tried to call the protected function '%s'."
L["No locals to dump"] = "No locals to dump"

--Distributor
L['%s is attempting to share his filters with you. Would you like to accept the request?'] = "%s хочет передать Вам свои фильтры. Желаете ли Вы принять их?"
L['%s is attempting to share the profile %s with you. Would you like to accept the request?'] = "%s хочет передать Вам профиль %s. Желаете ли Вы принять его?"
L["Data From: %s"] = "Данные от: %s"
L['Filter download complete from %s, would you like to apply changes now?'] = "Завершена загрузка фильтров от %s. Желаете применить изменения сейчас?"
L["Lord! It's a miracle! The download up and vanished like a fart in the wind! Try Again!"] = "Чтоб его! Загрузка была... да всплыла. Попробуйте еще раз!"
L['Profile download complete from %s, but the profile %s already exists. Change the name or else it will overwrite the existing profile.'] = "Загрузка профиля от %s завершена, но профиль %s уже существует. Измените его название или он перезапишет уже существующий профиль."
L['Profile download complete from %s, would you like to load the profile %s now?'] = "Загрузка профиля от %s завершена, хотите загрузить профиль %s сейчас?"
L['Profile request sent. Waiting for response from player.'] = "Запрос на передачу профиля отправлен. Ждите, пожалуйста, ответа."
L['Request was denied by user.'] = "Запрос отклонен пользователем."
L['Your profile was successfully recieved by the player.'] = "Ваш профиль успешно получен целью. Ура, товарищи!"

--Install
L["Auras Set"] = "Ауры установлены"
L["Auras System"] = "Система аур"
L['Caster DPS'] = "Заклинатель"
L["Chat Set"] = "Чат настроен"
L["Chat"] = "Чат"
L['Choose a theme layout you wish to use for your initial setup.'] = "Выберите тему, которую Вы хотите использовать."
L["Classic"] = "Классическая"
L["Click the button below to resize your chat frames, unitframes, and reposition your actionbars."] = "Нажмите кнопку ниже для изменения размеров вашего чата, рамок юнитов и перемещения ваших панелей действий."
L['Config Mode:'] = "Режим настройки:"
L["CVars Set"] = "Настройки сброшены"
L["CVars"] = "Настройки игры"
L['Dark'] = "Темная"
L['Disable'] = "Выключить"
L["ElvUI Installation"] = "Установка ElvUI"
L["Finished"] = "Завершить"
L['Grid Size:'] = "Размер сетки"
L['Healer'] = "Лекарь"
L["High Resolution"] = "Высокое разрешение"
L["high"] = "высоким"
L['Icons Only'] = "Только иконки" --Also used in Bags
L["If you have an icon or aurabar that you don't want to display simply hold down shift and right click the icon for it to disapear."] = "Если Вы видите иконку или полосу аур, которую Вы не хотите отображать, просто зажмите shift и кликните на иконке правой кнопкой, чтобы она исчезла."
L["Importance: |cff07D400High|r"] = "Важность: |cff07D400Высокая|r"
L["Importance: |cffD3CF00Medium|r"] = "Важность: |cffD3CF00Средняя|r"
L["Importance: |cffFF0000Low|r"] = "Важность: |cffFF0000Низкая|r"
L["Installation Complete"] = "Установка завершена"
L['Integrated'] = "Интегрированная"
L["Layout Set"] = "Расположение установлено"
L["Layout"] = "Расположение"
L["Lock"] = "Закрепить"
L['Low Resolution'] = "Низкое разрешение"
L["low"] = "низким"
L["Movers unlocked. Move them now and click Lock when you are done."] = "Блокировка отключена. Передвиньте фреймы и нажмите 'Закрепить', когда закончите."
L['Nudge'] = "Сдвиг"
L['Physical DPS'] = "Физический урон"
L["Pixel Perfect Set"] = "Pixel Perfect установлен"
L["Pixel Perfect"] = "Pixel Perfect"
L["Please click the button below so you can setup variables and ReloadUI."] = "Пожалуйста, нажмите кнопку ниже для установки переменных и перезагрузки интерфейса."
L["Please click the button below to setup your CVars."] = "Пожалуйста, нажмите кнопку ниже для сброса настроек."
L["Please press the continue button to go onto the next step."] = "Пожалуйста, нажмите кнопку 'Продолжить' для перехода к следующему шагу"
L["Resolution Style Set"] = "Разрешение установлено"
L["Resolution"] = "Разрешение"
L["Select the type of aura system you want to use with ElvUI's unitframes. The integrated system utilizes both aura-bars and aura-icons. The icons only system will display only icons and aurabars won't be used. The classic system will configure your auras to be default."] = "Выберите тип системы аур, которую вы хотите использовать на рамках юнитов ElvUI. Интегрированная система использует и иконки, и полосы аур. Система иконок использует только иконки, полосы аур не будут использоваться. Классическая система настроит ауры на умолчания."
L["Setup Chat"] = "Настроить чат"
L["Setup CVars"] = "Сбросить настройки"
L["Skip Process"] = "Пропустить установку"
L["Sticky Frames"] = "Клейкие фреймы"
L['Tank'] = "Танк"
L["The chat windows function the same as Blizzard standard chat windows, you can right click the tabs and drag them around, rename, etc. Please click the button below to setup your chat windows."] = "Окна чата работают так же, как и в стандартном чате Blizzard. Вы можете нажать правую кнопку мыши на вкладках для перемещения, переименования и тд. Пожалуйста, нажмите кнопку ниже для настройки чата."
L["The in-game configuration menu can be accesses by typing the /ec command or by clicking the 'C' button on the minimap. Press the button below if you wish to skip the installation process."] = "Меню настроек можно вызвать командой /ес или кнопкой 'С' на миникарте. Нажмите кнопку ниже, если Вы хотите прервать процесс установки."
L['The Pixel Perfect option will change the overall apperance of your UI. Using Pixel Perfect is a slight performance increase over the traditional layout.'] = "Опция Pixel PErfect изменит вид интерфейса. Использование этой опции даст небольшое улучшение производительности в стравнении с традиционным видом."
L["Theme Set"] = "Тема установлена"
L['Theme Setup'] = "Тема"
L["This install process will help you learn some of the features in ElvUI has to offer and also prepare your user interface for usage."] = "Этот процесс установки поможет Вам узнать о некоторых функциях ElvUI и подготовить Ваш интерфейс к использованию."
L["This is completely optional."] = "Это действие абсолютно не обязательно."
L["This part of the installation process sets up your chat windows names, positions and colors."] = "Эта часть установки настроит названия, позиции и цвета вкладок чата."
L["This part of the installation process sets up your World of Warcraft default options it is recommended you should do this step for everything to behave properly."] = "Эта часть установки сбросит настройки World of Warcraft на конфигурацию по умолчанию. Рекомендуется выполнить этот шаг для надлежащей работы интерфейса."
L["This resolution doesn't require that you change settings for the UI to fit on your screen."] = "Для соответствия интерфейса вашему экрану не требуется изменения настроек."
L["This resolution requires that you change some settings to get everything to fit on your screen."] = "Для соответствия интерфейса вашему экрану требуется изменение некоторых настроек."
L["This will change the layout of your unitframes, raidframes, and datatexts."] = "Это изменит расположение ваших рамок юнитов, рейда и информационных текстов"
L['Trade'] = "Торговля"
L['Using the healer layout it is highly recommended you download the addon Clique to work side by side with ElvUI.'] = "Для использования настроек лекаря крайне рекомендуется установка аддона Clique, который всесторонне поддерживается ElvUI."
L['Using this option will cause your borders around frames to be 1 pixel wide instead of 3 pixel. You may have to finish the installation to notice a differance. By default this is enabled.'] = "Использование этой опции сделаем границы вокруг фреймов шириной в 1 пиксейль вместо 3х. Вам может понадобиться завершить установку для того, чтобы заметить разницу. По умолчанию, опция включена."
L["Welcome to ElvUI version %s!"] = "Добро пожаловать в ElvUI версии %s!"
L["You are now finished with the installation process. If you are in need of technical support please visit us at http://www.tukui.org."] = "Вы завершили процесс установки. Если Вам требуется техническая поддержка, посетите сайт http://www.tukui.org."
L['You can always change fonts and colors of any element of elvui from the in-game configuration.'] = "Вы всегда можете изменить шрифты и цвета любого элемента ElvUI из меню конфигурации. Классическая и пиксельная темы не отличаются для русского клиента."
L["You can now choose what layout you wish to use based on your combat role."] = "Вы можете выбрать используемое расположение, основываясь на Вашей роли."
L["You may need to further alter these settings depending how low you resolution is."] = "Вам может понадобиться дальнейшее изменение этих настроек в зависимости от того, насколько низким является ваше разрешение."
L["Your current resolution is %s, this is considered a %s resolution."] = "Ваше текущее разрешение - %s, это считается %s разрешением."

--Misc
L['Bars'] = true; --Also used in UnitFrames
L['Calendar'] = true;
L["Can't Roll"] = true;
L['Disband Group'] = true;
L['Empty Slot'] = true;
L["Enable"] = true; --Doesn't fit a section since it's used a lot of places
L['Experience'] = true;
L['Fishy Loot'] = true;
L['Left Click:'] = true; --layout\layout.lua
L['Raid Menu'] = true;
L['Remaining:'] = true;
L['Rested:'] = true;
L['Right Click:'] = true; --layout\layout.lua
L['Show BG Texts'] = true; --layout\layout.lua
L['Toggle Chat Frame'] = true; --layout\layout.lua
L['Toggle Configuration'] = true; --layout\layout.lua
L['XP:'] = true;
L["You don't have permission to mark targets."] = true;
L['ABOVE_THREAT_FORMAT'] = '%s: %.0f%% [%.0f%% above |cff%02x%02x%02x%s|r]'

--Movers
L[' Frames'] = true;
L['Alternative Power'] = true;
L['Arena Frames'] = true; --Also used in UnitFrames
L["Auras Frame"] = true;
L['Bags'] = true; --Also in DataTexts
L['Bar '] = true; --Also in ActionBars
L['BNet Frame'] = true;
L['Boss Button'] = true;
L['Boss Frames'] = true; --Also used in UnitFrames
L["Experience Bar"] = true;
L['Focus Castbar'] = true;
L['Focus Frame'] = true; --Also used in UnitFrames
L['FocusTarget Frame'] = true; --Also used in UnitFrames
L["GM Ticket Frame"] = true;
L["Left Chat"] = true;
L["Loot / Alert Frames"] = true;
L["Loot Frame"] = true;
L['Loss Control Icon'] = true;
L['MA Frames'] = true;
L['Micro Bar'] = true; --Also in ActionBars
L['Minimap'] = true;
L['MT Frames'] = true;
L['Party Frames'] = true; --Also used in UnitFrames
L['Pet Bar'] = true; --Also in ActionBars
L['Pet Frame'] = true; --Also used in UnitFrames
L['PetTarget Frame'] = true; --Also used in UnitFrames
L['Player Castbar'] = true;
L['Player Frame'] = true; --Also used in UnitFrames
L['Raid 1-'] = true;
L["Reputation Bar"] = true;
L["Right Chat"] = true;
L['Stance Bar'] = true; --Also in ActionBars
L['Target Castbar'] = true;
L['Target Frame'] = true; --Also used in UnitFrames
L['TargetTarget Frame'] = true; --Also used in UnitFrames
L['Tooltip'] = true;
L['Totems'] = true;
L["Vehicle Seat Frame"] = true;
L['Watch Frame'] = true;
L['Weapons'] = true;

--NamePlates
L['Discipline'] = true;
L['Holy'] = true;
L['Mistweaver'] = true;
L['Restoration'] = true;

--Prints
L[" |cff00ff00bound to |r"] = true;
L["%s frame(s) has a conflicting anchor point, please change either the buff or debuff anchor point so they are not attached to each other. Forcing the debuffs to be attached to the main unitframe until fixed."] = true;
L["All keybindings cleared for |cff00ff00%s|r."] = true;
L['Already Running.. Bailing Out!'] = true;
L['Battleground datatexts temporarily hidden, to show type /bgstats or right click the "C" icon near the minimap.'] = true;
L['Battleground datatexts will now show again if you are inside a battleground.'] = true;
L['Binds Discarded'] = true;
L['Binds Saved'] = true;
L['Confused.. Try Again!'] = true;
L['Deleted %d gray items. Total Worth: %s'] = true;
L['No gray items to delete.'] = true;
L['No gray items to sell.'] = true;
L['The spell "%s" has been added to the Blacklist unitframe aura filter.'] = true;
L['Vendored gray items for:'] = true;
L["You don't have enough money to repair."] = true;
L['You must be at a vendor.'] = true;
L['Your items have been repaired for: '] = true;
L['Your items have been repaired using guild bank funds for: '] = true;
L["Your version of ElvUI is out of date. You can download the latest version from http://www.tukui.org"] = true;
L['|cFFE30000Lua error recieved. You can view the error message when you exit combat.'] = true;
L['LOGIN_MSG'] = "Welcome to %sElvUI|r version %s%s|r, type /ec to access the in-game configuration menu. If you are in need of technical support you can visit us at http://www.tukui.org"

--Static Popups
L["A setting you have changed will change an option for this character only. This setting that you have changed will be uneffected by changing user profiles. Changing this setting requires that you reload your User Interface."] = true;
L["Are you sure you want to delete all your gray items?"] = true;
L["Are you sure you want to disband the group?"] = true;
L["Are you sure you want to reset every mover back to it's default position?"] = true;
L["Because of the mass confusion caused by the new aura system I've implemented a new step to the installation process. This is optional. If you like how your auras are setup go to the last step and click finished to not be prompted again. If for some reason you are prompted repeatedly please restart your game."] = true;
L["Can't buy anymore slots!"] = true;
L['Disable Warning'] = true;
L['Discard'] = true;
L['Do you swear not to post in technical support about something not working without first disabling the addon/module combination first?'] = true;
L["Hover your mouse over any actionbutton or spellbook button to bind it. Press the escape key or right click to clear the current actionbutton's keybinding."] = true;
L['I Swear'] = true;
L['Oh lord, you have got ElvUI and Tukui both enabled at the same time. Select an addon to disable.'] = true;
L["One or more of the changes you have made require a ReloadUI."] = true;
L["One or more of the changes you have made will effect all characters using this addon. You will have to reload the user interface to see the changes you have made."] = true;
L['Save'] = true;
L["You have changed the pixel perfect option. You will have to complete the installation process to remove any graphical bugs."] = true;
L['You have changed your UIScale, however you still have the AutoScale option enabled in ElvUI. Press accept if you would like to disable the Auto Scale option.'] = true;
L['You must purchase a bank slot first!'] = true;
L["INCOMPATIBLE_ADDON"] = "The addon %s is not compatible with ElvUI's %s module. Please select either the addon or the ElvUI module to disable."

--Tooltip
L['Count'] = true;
L['Targeted By:'] = true;

--Tutorials
L['A raid marker feature is available by pressing Escape -> Keybinds scroll to the bottom under ElvUI and setting a keybind for the raid marker.'] = true;
L['ElvUI has a dual spec feature which allows you to load different profiles based on your current spec on the fly. You can enable this from the profiles tab.'] = true;
L['For technical support visit us at http://www.tukui.org.'] = true;
L['If you accidently remove a chat frame you can always go the in-game configuration menu, press install, go to the chat portion and reset them.'] = true
L['If you are experiencing issues with ElvUI try disabling all your addons except ElvUI, remember ElvUI is a full UI replacement addon, you cannot run two addons that do the same thing.'] = true;
L['The buff panel to the right of minimap is a list of your consolidated buffs. You can disable it in Buffs and Debuffs options of ElvUI.'] = true;
L['The focus unit can be set by typing /focus when you are targeting the unit you want to focus. It is recommended you make a macro to do this.'] = true;
L['To move abilities on the actionbars by default hold shift + drag. You can change the modifier key from the actionbar options menu.'] = true;
L['To setup which channels appear in which chat frame, right click the chat tab and go to settings.'] = true;
L['Using the /farmmode <size> command will spawn a larger minimap on your screen that can be moved around, very useful when farming.'] = true;
L['You can access copy chat and chat menu functions by mouse over the top right corner of chat panel and left/right click on the button that will appear.'] = true;
L['You can see someones average item level of their gear by holding shift and mousing over them. It should appear inside the tooltip.'] = true;
L['You can set your keybinds quickly by typing /kb.'] = true;
L['You can toggle the microbar by using your middle mouse button on the minimap you can also accomplish this by enabling the actual microbar located in the actionbar settings.'] = true;
L['You can use the /resetui command to reset all of your movers. You can also use the command to reset a specific mover, /resetui <mover name>.\nExample: /resetui Player Frame'] = true;

--UnitFrames
L['Ghost'] = true;
L['Offline'] = true;